name: choreo
channels:
  - conda-forge
dependencies:
  - python=3.13.2
  # - emscripten=3.1.58
  - pyodide-build=0.30.5
  - mpmath
  - matplotlib
  - scipy
  - networkx
  - cython
  - ffmpeg
  - fftw
  - tbb 
  - ffmpeg-python
  - pip
  - mkl_fft
  - ducc0
  - pyamg
  - numba
  - pytest
  - pytest-xdist
  - attrs
  - Sphinx
  - pydata-sphinx-theme
  - sphinx-gallery
  - sphinx-needs
  - pyquickbench
  - threadpoolctl
  - pyfftw>=0.14.0
  - pip:
    - sphinx-pyproject
    - sphinx-test-reports
    - sphinxcontrib.plantuml